(()=>{
  const $=id=>document.getElementById(id);
  const authModal=$('authModal'),adminModal=$('adminModal'),authForm=$('authForm'),adminUsers=$('adminUsers');
  let currentUser=null,setupMode=false;
  const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const headerActions=document.querySelector('.topbar>div:last-child');
  const accountLabel=document.createElement('span');accountLabel.id='accountLabel';accountLabel.className='account-chip';accountLabel.textContent='ACCESS CHECK';
  const accessButton=document.createElement('button');accessButton.id='adminPanel';accessButton.className='ghost-btn';accessButton.textContent='Manage access';accessButton.hidden=true;
  const signOutButton=document.createElement('button');signOutButton.id='signOut';signOutButton.className='ghost-btn';signOutButton.textContent='Sign out';signOutButton.hidden=true;
  headerActions.prepend(accountLabel,accessButton);headerActions.append(signOutButton);$('addUserForm').elements.role.innerHTML='<option value="user">User</option><option value="trusted">Trusted</option><option value="council">Council</option><option value="leader">Leader</option><option value="admin">Admin</option>';
  async function request(url,options={}){const response=await fetch(url,options);let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw new Error(payload.error||`Request failed (${response.status})`);return payload}
  async function restoreAccountPreferences(){try{await window.loadAccountPreferences?.()}catch(error){console.warn('Could not restore account preferences:',error)}}
  function setPermissions(user){currentUser=user||null;const rank=['user','trusted','council','leader','admin'].indexOf(currentUser?.role);window.atlasCanEdit=()=>rank>=1;window.atlasCanManageLocal=()=>rank>=2;window.atlasCanConnect=()=>rank>=3;window.atlasCanAdmin=()=>rank===4;accountLabel.textContent=currentUser?`${currentUser.display_name.toUpperCase()} · ${currentUser.role.toUpperCase()}`:'SIGNED OUT';accessButton.hidden=!window.atlasCanAdmin();$('connectMysql').hidden=!window.atlasCanConnect();signOutButton.hidden=!currentUser;}
  function setAuthMode(setup){setupMode=setup;$('authEyebrow').textContent=setup?'FIRST-RUN SETUP':'ATLAS ACCESS';$('authTitle').textContent=setup?'Create the first administrator':'Sign in to the atlas';$('authIntro').textContent=setup?'Create the administrator account that will manage Atlas access.':'Use your Atlas account to view the shared navigation map.';$('authDisplayWrap').hidden=!setup;$('authDisplayName').required=setup;$('authPassword').autocomplete=setup?'new-password':'current-password';$('authSubmit').textContent=setup?'Create administrator':'Sign in';$('authSwitch').hidden=!setup;$('authError').textContent='';}
  async function checkSession(){try{const response=await window.atlasFetch('/api/auth/session',{headers:window.atlasAccessToken?{Authorization:`Bearer ${window.atlasAccessToken}`}:{}});const data=await response.json();if(data.user){setPermissions(data.user);authModal.classList.add('hidden');await restoreAccountPreferences();await loadDatabase();return}setPermissions(null);setAuthMode(Boolean(data.setup_required));authModal.classList.remove('hidden')}catch{setPermissions(null);setAuthMode(false);$('authError').textContent='Cannot reach the local Atlas server.';authModal.classList.remove('hidden')}}
  authForm.onsubmit=async event=>{event.preventDefault();const error=$('authError'),button=$('authSubmit'),payload=Object.fromEntries(new FormData(authForm));button.disabled=true;error.textContent='';try{const data=await request(setupMode?'/api/auth/setup':'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});window.atlasAccessToken=data.token;sessionStorage.setItem('se-atlas-token',data.token);setPermissions(data.user);authModal.classList.add('hidden');authForm.reset();await restoreAccountPreferences();await loadDatabase()}catch(err){error.textContent=err.message}finally{button.disabled=false}};
  $('authModeToggle').onclick=()=>setAuthMode(true);
  function clearAtlasData(){nodes.splice(0,nodes.length);clusters.splice(0,clusters.length);regions.splice(0,regions.length);selected=null;focusedRegion=null;focusedCluster=null;renderSectors();renderList();showEmptySelection();draw();$('datasetStatus').textContent='AUTH REQUIRED';}
  signOutButton.onclick=async()=>{try{await request('/api/auth/logout',{method:'POST'})}catch{}window.resetAccountPreferences?.();window.atlasAccessToken='';sessionStorage.removeItem('se-atlas-token');clearAtlasData();setPermissions(null);setAuthMode(false);authModal.classList.remove('hidden');};
  document.addEventListener('click',event=>{const editControl=event.target.closest('#addLocation,#editSelected,#deleteSelected'),curationControl=event.target.closest('#editRegion,#editRegionDetails,#editClusterDetails'),connectControl=event.target.closest('#connectMysql');if((editControl&&!window.atlasCanEdit())||(curationControl&&!window.atlasCanManageLocal())||(connectControl&&!window.atlasCanConnect())){event.preventDefault();event.stopImmediatePropagation();window.alert(editControl?'Trusted access is required for GPS changes.':curationControl?'Council access is required to edit region or cluster details.':'Leader access is required to connect MySQL.')}},true);
  document.addEventListener('submit',event=>{if(['locationForm','editForm'].includes(event.target.id)&&!window.atlasCanEdit()){event.preventDefault();event.stopImmediatePropagation();window.alert('Trusted access is required for GPS changes.')}if(['regionForm','clusterForm'].includes(event.target.id)&&!window.atlasCanManageLocal()){event.preventDefault();event.stopImmediatePropagation();window.alert('Council access is required to edit region or cluster details.')}if(event.target.id==='dbForm'&&!window.atlasCanConnect()){event.preventDefault();event.stopImmediatePropagation();window.alert('Leader access is required to connect MySQL.')}},true);
  async function loadUsers(){const data=await request('/api/users');adminUsers.innerHTML=data.users.map(user=>`<article class="access-user ${user.is_active?'':'inactive'}" data-user-id="${user.id}"><div><strong>${escapeHtml(user.display_name)}</strong><small>@${escapeHtml(user.username)} · ${user.is_active?'Active':'Disabled'}</small></div><select class="user-role" aria-label="${escapeHtml(user.display_name)} role"><option value="user" ${user.role==='user'?'selected':''}>User</option><option value="trusted" ${user.role==='trusted'?'selected':''}>Trusted</option><option value="council" ${user.role==='council'?'selected':''}>Council</option><option value="leader" ${user.role==='leader'?'selected':''}>Leader</option><option value="admin" ${user.role==='admin'?'selected':''}>Admin</option></select><button type="button" class="mini-btn user-toggle">${user.is_active?'Disable':'Enable'}</button><input class="user-password" type="password" minlength="8" placeholder="New password (optional)" aria-label="Reset password for ${escapeHtml(user.display_name)}" /><div class="user-actions"><button type="button" class="mini-btn user-save">Save</button><button type="button" class="mini-btn danger-btn user-delete">Delete</button></div></article>`).join('')||'<p class="position-empty">No access accounts found.</p>';}
  accessButton.onclick=async()=>{try{$('adminError').textContent='';await loadUsers();adminModal.classList.remove('hidden')}catch(err){$('adminError').textContent=err.message;adminModal.classList.remove('hidden')}};
  $('closeAdminModal').onclick=()=>adminModal.classList.add('hidden');
  $('addUserForm').onsubmit=async event=>{event.preventDefault();const form=event.target,error=$('adminError'),button=form.querySelector('button');button.disabled=true;error.textContent='';try{await request('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await loadUsers()}catch(err){error.textContent=err.message}finally{button.disabled=false}};
  adminUsers.onclick=async event=>{const card=event.target.closest('[data-user-id]');if(!card)return;const id=card.dataset.userId,error=$('adminError');error.textContent='';try{if(event.target.classList.contains('user-delete')){if(!confirm('Delete this user account? This cannot be undone.'))return;await request(`/api/users/${id}`,{method:'DELETE'});await loadUsers();return}if(event.target.classList.contains('user-toggle')){const active=event.target.textContent==='Enable';await request(`/api/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_active:active})});await loadUsers();return}if(event.target.classList.contains('user-save')){await request(`/api/users/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:card.querySelector('.user-role').value,password:card.querySelector('.user-password').value})});await loadUsers()}}catch(err){error.textContent=err.message}};
  checkSession();
})();
